### PR TITLE
Introduce Prettier and reconfigure ESLint

### PR DESCRIPTION
**Pull request by danieldiekmeier**

### CODE REVIEW

**Comment by timomeh** [comment]
@danieldiekmeier Could you maybe tell me which files I should take a look at? 😄

**Comment by danieldiekmeier** [comment]
Welp. :D

I think most if the changes are just noise from Prettier and Linting.

In this commit, I changed the Node version on Travis: https://github.com/wdr-data/code4maus/pull/62/commits/d86503b35dd1d6613dd3e89233459f2a79037e10

While linting, I removed some `props` destructuring, but it turns out that some components relied on the HOCs filtering out some of the props before passing them along. To fix this, I had to reintroduce the props in this commit: https://github.com/wdr-data/code4maus/pull/62/commits/faba689cb4ed4c59dadd0150c48f4881a4fecd12

**Comment by danieldiekmeier** [comment]
Maybe also take a look at the one root `.eslintrc.json` that replaces all the other ESLint configs!

**Review by timomeh — APPROVED** [review]
In addition to the two commits you commented, I also looked at the package.json and eslint config. Looks all good to me.

**Pull request merged**
